version: "3"

services:
    mysql-server:
        image: mysql:5.7
        container_name: mysql-server
        volumes:
            - '/data/mysql:/var/lib/mysql'
        ports:
            - '3306:3306'
        environment:
            - MYSQL_DATABASE=zabbix
            - MYSQL_USER=zabbix
            - MYSQL_PASSWORD=zabbix_pwd
            - MYSQL_ROOT_PASSWORD=root_pwd
            
    zabbix-java-gateway:
        image: zabbix/zabbix-java-gateway
        container_name: zabbix-java-gateway
        
    zabbix-server-mysql:
        image: zabbix/zabbix-server-mysql
        container_name: zabbix-server-mysql
        environment:
            - DB_SERVER_HOST=mysql-server
            - MYSQL_DATABASE=zabbix
            - MYSQL_USER=zabbix
            - MYSQL_PASSWORD=zabbix_pwd
            - MYSQL_ROOT_PASSWORD=root_pwd
            - ZBX_JAVAGATEWAY=zabbix-java-gateway
        links:
            - 'mysql-server:mysql'
            - 'zabbix-java-gateway:zabbix-java-gateway'
        ports:
            - '10051:10051'
            
    zabbix-app:
        image: zabbix/zabbix-web-nginx-mysql
        container_name: zabbix-app
        environment:
            - TZ=America/Sao_Paulo
            - PHP_TZ=America/Sao_Paulo
            - DB_SERVER_HOST=mysql-server
            - MYSQL_DATABASE=zabbix
            - MYSQL_USER=zabbix
            - MYSQL_PASSWORD=zabbix_pwd
            - MYSQL_ROOT_PASSWORD=root_pwd
        links:
            - 'mysql-server:mysql'
            - 'zabbix-server-mysql:zabbix-server'
        ports:
            - '8090:80'
        
        
